"""empty message

Revision ID: 2747335a936c
Revises: 
Create Date: 2025-12-27 07:21:22.011564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2747335a936c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('COMMIT', 'ISSUE', 'RELEASE', name='eventtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('repository', sa.String(length=200), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('commit_hash', sa.String(length=100), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('release_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_events_event_id'), 'github_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_events_event_id'), table_name='github_events')
    op.drop_table('github_events')
    # ### end Alembic commands ###
